CREATE OR REPLACE FUNCTION LAST_LOGIN_UPDATE()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.last_login :=NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRIGGER_LAST_LOGIN
BEFORE UPDATE ON USERS
FOR EACH ROW
WHEN (OLD.LAST_LOGIN IS DISTINCT FROM NEW.LAST_LOGIN)
EXECUTE FUNCTION LAST_LOGIN_UPDATE();